# Generated by Django 3.1.3 on 2020-11-25 13:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('aboutme', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('display_photo', cloudinary.models.CloudinaryField(default="url_for('image.jpg')", max_length=255, verbose_name='image')),
                ('followers', models.CharField(default=0, max_length=255)),
                ('following', models.CharField(default=0, max_length=255)),
                ('bio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clone.bio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(max_length=255)),
                ('username', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='clone.bio')),
            ],
        ),
    ]
