# Generated by Django 3.1.3 on 2020-11-22 21:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20201122_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='display_photo',
        ),
    ]
