# Generated by Django 3.1.3 on 2020-11-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_auto_20201122_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
